title: Programiranje 1
author: Matija Pretnar
exclude_patterns:
  - odlozisce/*
repository:
  url: 'https://github.com/matijapretnar/programiranje-1'
  book_path: zapiski
  branch: zapiski
only_build_toc_files: true